name: flutter_core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^4.2.1
  get_it: ^7.2.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter: